# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master
- dev

variables:
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}: 
    export_command: lint-master
    bucket_name: thecanabrava-libtest-master
  ${{ if eq(variables['Build.SourceBranchName'], 'dev') }}: 
    export_command: export-dev
    bucket_name: thecanabrava-libtest-dev

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm install -g expo-cli
    npm run $(export_command)
  displayName: '$(export_command) and $(bucket_name)'

#- task: S3Upload@1
#  inputs:
#    awsCredentials: 'Upload to S3'
#    regionName: 'us-west-2'
#    bucketName: '$(bucket_name)'
#    sourceFolder: '$(System.DefaultWorkingDirectory)/dist'
#    globExpressions: '**'
#    filesAcl: 'public-read'
