# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm install -g expo-cli


    npx expo export -p https://thecanabrava-libtest.s3-us-west-2.amazonaws.com -f
    npm run upload -- --id AKIA3AQGWMKLO52WVMXU --secret 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
  displayName: 'npm install and export'